//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eligibilite
    {
        public string Nom_Incube { get; set; }
        public string Projet { get; set; }
        public Nullable<int> Tot_Participation { get; set; }
        public Nullable<int> Nombre_Present { get; set; }
        public Nullable<int> Nombre_Absence { get; set; }
        public string P_Participation_Total { get; set; }
        public string Observation { get; set; }
    }
}
