//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EclosionHubEntities : DbContext
    {
        public EclosionHubEntities()
            : base("name=EclosionHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeQR> CodeQRs { get; set; }
        public virtual DbSet<Entreprisee> Entreprisees { get; set; }
        public virtual DbSet<Incube> Incubes { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Presence> Presences { get; set; }
        public virtual DbSet<Eligibilite> Eligibilites { get; set; }
        public virtual DbSet<RapportDePresenceComplet> RapportDePresenceComplets { get; set; }
        public virtual DbSet<RapportParticipationTotalParModule> RapportParticipationTotalParModules { get; set; }
        public virtual DbSet<RapportPresenceParModule> RapportPresenceParModules { get; set; }
        public virtual DbSet<RapportPresenceParSessionParModule> RapportPresenceParSessionParModules { get; set; }
        public virtual DbSet<VueObservationsIncube> VueObservationsIncubes { get; set; }
        public virtual DbSet<VueListProjetConc> VueListProjetConcs { get; set; }
        public virtual DbSet<VueModuleConc> VueModuleConcs { get; set; }
        public virtual DbSet<VuePresence> VuePresences { get; set; }
    }
}
