//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Presences = new HashSet<Presence>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public System.DateTime Date_debut { get; set; }
        public System.DateTime Date_fin { get; set; }
        public System.TimeSpan Heure_debut { get; set; }
        public System.TimeSpan Heure_fin { get; set; }
        public string Formateur { get; set; }
        public string Description { get; set; }
        public string Statut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence> Presences { get; set; }
    }
}
