//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int Id { get; set; }
        public int Incube { get; set; }
        public int Module { get; set; }
        public string Present { get; set; }
        public System.TimeSpan heure_arrive { get; set; }
        public System.TimeSpan heure_sortie { get; set; }
        public System.DateTime Date_Scan { get; set; }
        public string Justification { get; set; }
    
        public virtual Incube Incube1 { get; set; }
        public virtual Module Module1 { get; set; }
    }
}
