//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapportPresenceParModule
    {
        public string Nom_Incube { get; set; }
        public string Entreprise { get; set; }
        public string Nom_Module { get; set; }
        public Nullable<int> N_Sessions { get; set; }
        public Nullable<int> Presences { get; set; }
        public Nullable<int> Absences { get; set; }
        public string P_Participation { get; set; }
        public string Observation { get; set; }
    }
}
