//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class VueModuleConc
    {
        public int id { get; set; }
        public string Module { get; set; }
        public string Debut { get; set; }
        public string Fin { get; set; }
        public Nullable<int> Tot_Sessions { get; set; }
        public string H_Debut { get; set; }
        public string H_Fin { get; set; }
        public string Formateur { get; set; }
        public string Statut { get; set; }
    }
}
