//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class VueObservationsIncube
    {
        public string N_Incube { get; set; }
        public string N_Module { get; set; }
        public string D_Scan { get; set; }
        public string J_Session { get; set; }
        public string H_D_Module { get; set; }
        public string H_Arrivee { get; set; }
        public string H_F_Module { get; set; }
        public string H_Sortie { get; set; }
        public string H_Formation { get; set; }
        public string H_Participation { get; set; }
        public string P_Participation { get; set; }
        public string Observation { get; set; }
    }
}
