//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclosionHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class VuePresence
    {
        public int id { get; set; }
        public string Incubes { get; set; }
        public string projet { get; set; }
        public string Participation { get; set; }
        public string Arrive { get; set; }
        public string Sortie { get; set; }
        public string Date { get; set; }
        public string Justification { get; set; }
        public string Module { get; set; }
    }
}
